editar e listar produtos
Maria26Fer/desafio-backend-m05-b2bt05- pull request #11
Opened 2023-10-19 22:32 UTC by arruda-amanda

2023-10-19 22:59 UTC, LarissaAngioni requested changes

2023-10-19 22:59 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +  const { usuarioLogado } = req;
não precisamos do usuário nesse controlador

2023-10-19 22:59 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +    const produtoEncontrado = await knex('produtos')
não precisa do returning, só usamos return com insert, update e delete

2023-10-19 22:59 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +    if (produtoEncontrado) {
não entendi

2023-10-19 22:59 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +      return res.status(401).json({ mensagem: "Já há um produto cadastrado com esse id" });
precisamos validar se o id do produto existe pra editar ele

2023-10-19 22:59 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +
falta as validações do joi pros campos obrigatórios

2023-10-20 12:16 UTC, LarissaAngioni requested changes

2023-10-20 12:16 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +
precisamos validar se o id da categoria existe no banco de dados, exemplos:. categoria_id: 1 ---> ok
categoria_id: 20 ---> Id da categoria não encontrado

2023-10-20 12:16 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +  const { usuarioLogado } = req;
o usuário vem do intermediário pelo req.usuario, mas também não precisamos do usuario nesse controlador

2023-10-20 12:16 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +    const usuarioLogadoId = knex("produtos").where("id_usuario", usuarioLogado.id);
não precisamos do usuário nesse controlador.
não existe a coluna "id_usuario" no banco de dados

2023-10-20 12:16 UTC, LarissaAngioni commented on src/controladores/produtos.js
> +      "any.required": "O campo quantidade_estoque deve ser informado.",
"any.required": "O campo quantidade de estoque deve ser informado."

2023-10-20 12:24 UTC, LarissaAngioni commented
![](https://github.trello.services/images/mini-trello-icon.png) [Editar dados do produto](https://trello.com/c/fNbHD2wE/3-editar-dados-do-produto)

2023-10-20 12:24 UTC, LarissaAngioni commented
![](https://github.trello.services/images/mini-trello-icon.png) [Listar produtos](https://trello.com/c/J4ftEv55/4-listar-produtos)

2023-10-20 14:13 UTC, arruda-amanda commented on src/controladores/produtos.js
> +    const produtoEncontrado = await knex('produtos')
corrigido

2023-10-20 15:55 UTC, arruda-amanda commented on src/controladores/produtos.js
> +      "any.required": "O campo quantidade_estoque deve ser informado.",
corrigido!

2023-10-20 17:54 UTC, merged